# Generated by Django 3.0.8 on 2021-01-05 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdventureClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=100)),
                ('contact', models.CharField(default='', max_length=11)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('club_address', models.CharField(max_length=150)),
                ('owner', models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdventureEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('overview', models.CharField(default='', max_length=256)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('event_start_date', models.DateField()),
                ('event_end_date', models.DateField()),
                ('event_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdventureClub.AdventureClub')),
            ],
        ),
        migrations.CreateModel(
            name='TouristReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourist_review', models.CharField(max_length=256)),
                ('adventureevent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdventureClub.AdventureEvent')),
                ('tourist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point', models.CharField(max_length=150, null=True)),
                ('destination', models.CharField(max_length=150, null=True)),
                ('booked_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdventureClub.AdventureEvent')),
            ],
        ),
    ]
