# Generated by Django 3.0.8 on 2021-01-05 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdventureClub', '0002_auto_20210105_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventureclub',
            name='city',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='adventureclub',
            name='owner',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
