# Generated by Django 3.1.4 on 2021-02-28 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdventureClub', '0003_auto_20210105_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventureevent',
            name='event_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myClub', to='AdventureClub.adventureclub'),
        ),
        migrations.AlterField(
            model_name='adventureevent',
            name='image',
            field=models.ImageField(null=True, upload_to='AdventureClub/media'),
        ),
    ]
