# Generated by Django 3.1.2 on 2021-03-01 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdventureClub', '0004_auto_20210228_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventureevent',
            name='event_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdventureClub.adventureclub'),
        ),
        migrations.AlterField(
            model_name='adventureevent',
            name='image',
            field=models.ImageField(null=True, upload_to='AdventureClub/AdventureEventPics'),
        ),
    ]
