# Generated by Django 3.1.4 on 2021-03-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdventureClub', '0006_auto_20210301_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventureclub',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adventureevent',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
