# Generated by Django 3.1.2 on 2021-03-08 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdventureClub', '0007_auto_20210306_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point', models.CharField(max_length=70, null=True)),
                ('destination', models.CharField(max_length=70, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='adventureclub',
            name='city',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='adventureclub',
            name='club_address',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='adventureclub',
            name='club_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='adventureevent',
            name='event_by',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='adventureevent',
            name='overview',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='adventureevent',
            name='title',
            field=models.CharField(max_length=80),
        ),
        migrations.DeleteModel(
            name='EventBooking',
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='booked_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdventureClub.adventureevent'),
        ),
    ]
