# Generated by Django 3.1.2 on 2021-03-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdventureClub', '0008_auto_20210308_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventureclub',
            name='club_image',
            field=models.ImageField(null=True, upload_to='AdventureClub/Club_Images'),
        ),
    ]
