# Generated by Django 3.0.8 on 2021-03-21 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdventureClub', '0009_adventureclub_club_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventureclub',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
