# Generated by Django 3.0.8 on 2021-03-21 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdventureClub', '0010_auto_20210321_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventureevent',
            name='event_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdventureClub.AdventureClub'),
        ),
    ]
